### ISSUE TITLE
Wayland Support

### ISSUE THREAD

**Issue by ibrahimkettaneh** [flathub/com.ticktick.TickTick#13]
Hello

I am  grateful to you for providing  this full featured package of TickTick.
I would greatly appreciate if you could add Wayland support to this app, please.

This would be more efficient, secure, and most importantly, would display more clearly and legibly for most users of this package who are certainly using Wayland.

Since this is an electron app, a couple ways to implement this would be:
1. Have it read ~/.config/electron25-flags.conf to determine the user's preference, and/or
2. See the Flatpak preferences and use the launch flag `--ozone-platform-hint=auto` if Wayland is preferred.

I greatly appreciate you providing this great package, and hope you find this feedback helpful. :smiley:

**Comment by gkeep** [comment]
Sadly, this does not work, as native Wayland is still not natively supported by the application, see also: https://github.com/flathub/com.ticktick.TickTick/pull/1#issuecomment-1123241708. 

Although I am (somehow) running TickTick on Wayland (did not do any tweaks like the ones you mentioned). Curious.
![image](https://github.com/flathub/com.ticktick.TickTick/assets/20600053/acb69bca-a713-4f28-9eac-70ab8a8186a0)

**Comment by ibrahimkettaneh** [comment]
Thank you for letting me know. 

This appears t obe something that the developers f the debian package can address.

The work you're doing is greatly appreciated. Thank you. :smile:
