### ISSUE TITLE
Update to 1.0.40

### ISSUE THREAD

**Issue by Skaldebane** [flathub/com.ticktick.TickTick#5]
Hi there! I'm new to this type of packaging, so I don't know how to contribute a PR by myself for the update.

Any guidance would be appreciated, or at least an update to 1.0.40, when possible.

**Comment by Skaldebane** [comment]
Actually, I'd just noticed that some Flathub bot here already submitted a pull request for the latest release automatically.

**Comment by daupaloffer** [comment]
Hey! My apologies, I've had a very busy few week. The update is now merged.

**Comment by Skaldebane** [comment]
Thanks!
